name: Deploy Strapi to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------
      # AWS LOGIN
      # --------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # --------------------
      # SETUP TERRAFORM FIRST
      # --------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # --------------------
      # LOGIN TO ECR
      # --------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --------------------
      # BUILD + PUSH IMAGE
      # --------------------
      - name: Build and Push Docker Image
        working-directory: strapi-app
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          REPO_NAME=$(cd ../terraform && terraform output -raw ecr_repository_url)

          echo "Repository: $REPO_NAME"
          echo "Tag: $IMAGE_TAG"

          docker build -t $REPO_NAME:$IMAGE_TAG .
          docker push $REPO_NAME:$IMAGE_TAG

      # --------------------
      # TERRAFORM DEPLOY
      # --------------------
      - name: Terraform Apply
        working-directory: terraform
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          REPO_NAME=$(terraform output -raw ecr_repository_url)
          IMAGE_URI="$REPO_NAME:$IMAGE_TAG"

          echo "Deploying image: $IMAGE_URI"

          terraform apply -auto-approve \
            -var="image_uri=$IMAGE_URI"
